version: '3'
services:
    solr:
      image: solr:9.5.0
      container_name: n11_solr
      ports:
      - "8983:8983"
      volumes:
      - ./data:/var/solr
      command:
      - solr-precreate
      - n11_restaurants