version: '3'
services:
  postgres_customers:
    image: postgres
    restart: always
    volumes:
      - ./pgdata/customers:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customers
    ports:
      - 50005:5432
    networks:
      - restaurant-panel

  postgres_logger:
    image: postgres
    restart: always
    volumes:
      - ./pgdata/logger:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logger
    ports:
      - 50008:5432
    networks:
      - restaurant-panel
networks:
  restaurant-panel:
    driver: bridge